Num_Z = 232
Hidden_Layer1 = 5
Hidden_Layer2 = 10
Hidden_Layer3 = Num_Z
LearningRate = 0.01
State_Size = 2
Action_Dim = 3
TAU = 0.01
z_max = 200
z_min = -2000
discount_rate = 0.95
sampling_size = 30
batch_size = 10
state_space = []
Open_Left = -100
Open_Right = 100
Tiger_Left = -100
Tiger_Right = 100
Listen = 0
Evade_reward = 10
Listen_reward = -1
Eaten_reward = -100
action_space = [Open_Left, Listen, Open_Right]
reward_space = [Evade_reward, Listen_reward, Eaten_reward]
real_state_space = [Tiger_Left, Tiger_Right]
Observation_space = [Tiger_Left, Tiger_Right]
MaxCTest = State_Size
b_h = [[0.5, 0.5]]
